[package]
edition = "2021"
name = "wenhu"
version = "0.1.0"

[dependencies]
anyhow = "1.0.96" 
clap = {version = "4.5.1", features = ["derive", "color"]}# 命令行支持      
colored = "2.1.0" # 颜色库
serde = {version = "1.0.218", features = ["derive"]} 
serde_yaml = "0.9.34"
